# Generated by Django 5.2.17 on 2026-08-12 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Raison Sociale')),
                ('nif', models.CharField(max_length=50, verbose_name='NIF')),
                ('stat', models.CharField(blank=True, max_length=50, null=True, verbose_name='STAT')),
                ('cnaps_no', models.CharField(max_length=50, verbose_name='N° CNaPS Employeur')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('activity', models.CharField(max_length=255, verbose_name='Activité Principale')),
                ('plan', models.CharField(choices=[('MONTHLY', '10 000 Ar / mois'), ('QUARTERLY', '25 000 Ar / 3 mois'), ('YEARLY', '100 000 Ar / an')], default='MONTHLY', max_length=20, verbose_name="Formule d'abonnement")),
                ('subscription_active', models.BooleanField(default=True, verbose_name='Abonnement Actif')),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
