# Generated by Django 5.2.17 on 2026-08-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_money_number', models.CharField(default='034 00 000 00', max_length=50, verbose_name='Numéro Mobile Money')),
                ('price', models.DecimalField(decimal_places=2, default=60000, max_digits=10, verbose_name="Prix de l'abonnement (Ar)")),
                ('instructions', models.TextField(default='Veuillez envoyer 60 000 Ar par Mobile Money avec la référence de votre entreprise.', verbose_name='Consignes de paiement')),
            ],
            options={
                'verbose_name': 'Configuration Paiement',
                'verbose_name_plural': 'Configuration Paiement',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='ban_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motif du bannissement'),
        ),
        migrations.AddField(
            model_name='company',
            name='generation_count',
            field=models.IntegerField(default=0, verbose_name='Nombre de fiches générées'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='Banni / Suspendu'),
        ),
        migrations.AddField(
            model_name='company',
            name='max_free_generations',
            field=models.IntegerField(default=3, verbose_name="Limite d'essais gratuits"),
        ),
        migrations.AlterField(
            model_name='company',
            name='plan',
            field=models.CharField(choices=[('STANDARD', '60 000 Ar / Abonnement')], default='STANDARD', max_length=20, verbose_name="Formule d'abonnement"),
        ),
        migrations.AlterField(
            model_name='company',
            name='subscription_active',
            field=models.BooleanField(default=False, verbose_name='Abonnement Actif'),
        ),
    ]
