# Generated by Django 5.2.17 on 2026-08-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_paymentsettings_company_ban_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='plan',
            field=models.CharField(choices=[('STANDARD', '60 000 Ar / 2 mois')], default='STANDARD', max_length=20, verbose_name="Formule d'abonnement"),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='instructions',
            field=models.TextField(default="Veuillez envoyer 60 000 Ar par Mobile Money (pour 2 mois d'accès) avec la référence ou le nom de votre entreprise.", verbose_name='Consignes de paiement'),
        ),
    ]
