# Generated by Django 5.2.17 on 2026-08-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_company_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsettings',
            name='instructions',
            field=models.TextField(default="Veuillez envoyer 60 000 Ar par Mobile Money (pour 2 mois d'accès) avec le nom de votre entreprise en référence.", verbose_name='Consignes de paiement'),
        ),
    ]
