# Generated by Django 5.2.17 on 2026-08-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_paymentsettings_instructions'),
    ]

    operations = [
        migrations.CreateModel(
            name='IRSASetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Paramètres IRSA Madagascar', max_length=100)),
                ('minimum_irsa', models.DecimalField(decimal_places=2, default=3000.0, max_digits=10, verbose_name='Minimum de perception (Ar)')),
                ('child_deduction_amount', models.DecimalField(decimal_places=2, default=2000.0, max_digits=10, verbose_name='Déduction par enfant (Ar)')),
                ('tranche_1_limit', models.DecimalField(decimal_places=2, default=350000.0, max_digits=10, verbose_name='Limite Tranche 1 (Ar)')),
                ('tranche_2_limit', models.DecimalField(decimal_places=2, default=400000.0, max_digits=10, verbose_name='Limite Tranche 2 (Ar)')),
                ('tranche_3_limit', models.DecimalField(decimal_places=2, default=500000.0, max_digits=10, verbose_name='Limite Tranche 3 (Ar)')),
                ('tranche_4_limit', models.DecimalField(decimal_places=2, default=600000.0, max_digits=10, verbose_name='Limite Tranche 4 (Ar)')),
                ('tranche_5_limit', models.DecimalField(decimal_places=2, default=4000000.0, max_digits=10, verbose_name='Limite Tranche 5 (Ar)')),
            ],
            options={
                'verbose_name': 'Configuration IRSA',
                'verbose_name_plural': 'Configuration IRSA',
            },
        ),
    ]
