# Generated by Django 5.2.17 on 2026-08-12 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('cin', models.CharField(max_length=50, verbose_name='N° CIN / Passeport')),
                ('job_title', models.CharField(max_length=100, verbose_name='Fonction')),
                ('contract_type', models.CharField(choices=[('CDD', 'CDD'), ('CDI', 'CDI')], default='CDD', max_length=10, verbose_name='Type de contrat')),
                ('hire_date', models.DateField(verbose_name="Date d'embauche")),
                ('department', models.CharField(default='Général', max_length=100, verbose_name='Département')),
                ('category', models.CharField(default='M1-1A', max_length=50, verbose_name='Catégorie Professionnelle')),
                ('cnaps_no', models.CharField(default='0', max_length=50, verbose_name='N° CNaPS Salarié')),
                ('children_count', models.IntegerField(default=0, verbose_name="Nombre d'enfants à charge")),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Salaire de Base (Ar)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20, verbose_name='Mois de Paie')),
                ('year', models.IntegerField(default=2026, verbose_name='Année')),
                ('working_days', models.IntegerField(default=30, verbose_name='Temps de travail (Jours/Heures)')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Heures supp. (h)')),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Gains Heures supp. (Ar)')),
                ('bonuses', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Primes et Indemnités (Ar)')),
                ('advances', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Avance sur salaire (Ar)')),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Salaire Brut')),
                ('cnaps_employee', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='CNaPS Salarié (1%)')),
                ('smids_employee', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='SMIDS Salarié')),
                ('taxable_base', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Base Imposable')),
                ('irsa', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='IRSA')),
                ('net_payable', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Net à Payer')),
                ('cnaps_employer', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='CNaPS Patronal (13%)')),
                ('smids_employer', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='SMIDS Patronal (5%)')),
                ('fmfp_employer', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='FMFP Patronal (1%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.employee')),
            ],
        ),
    ]
