# Generated by Django 5.2.17 on 2026-08-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='unpaid_absences_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Retenues Absences (Ar)'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='cnaps_employee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='CNaPS Salarié (1%)'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='cnaps_employer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='CNaPS Patronal (13%)'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='fmfp_employer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='FMFP Patronal (1%)'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Salaire Brut'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='irsa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='IRSA'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='net_payable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Net à Payer'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='smids_employee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='SMIDS Salarié'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='smids_employer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='SMIDS Patronal (5%)'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='taxable_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Base Imposable'),
        ),
    ]
