# Generated by Django 5.2.17 on 2026-08-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payslip_unpaid_absences_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='total_advance_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Solde Avance globale en cours (Ar)'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='absence_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name="Nombre de jours d'absence"),
        ),
        migrations.AddField(
            model_name='payslip',
            name='daily_absence_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Retenue par jour d'absence (Ar)"),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='advances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Retenue Avance sur salaire du mois (Ar)'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='unpaid_absences_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Retenues Absences (Ar)'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='working_days',
            field=models.IntegerField(default=30, verbose_name='Temps de travail (Jours)'),
        ),
    ]
