# Generated by Django 5.2.17 on 2026-08-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_employee_total_advance_balance_payslip_absence_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Masqué/Archivé'),
        ),
    ]
