# Generated by Django 5.2.17 on 2026-08-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_payslip_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='leave_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Solde de congés restants (Jours)'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='paid_leave_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Nombre de jours de congé payé pris'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='absence_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name="Nombre de jours d'absence non payés"),
        ),
    ]
