# Generated by Django 5.2.17 on 2026-08-18 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_paymentsettings_instructions'),
        ('payroll', '0005_employee_leave_balance_payslip_paid_leave_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnaps_employee_rate', models.DecimalField(decimal_places=4, default=0.01, max_digits=5, verbose_name='Taux CNaPS Salarié')),
                ('cnaps_employer_rate', models.DecimalField(decimal_places=4, default=0.13, max_digits=5, verbose_name='Taux CNaPS Patronal')),
                ('smids_employer_rate', models.DecimalField(decimal_places=4, default=0.05, max_digits=5, verbose_name='Taux SMIDS / OSTIE Patronal')),
                ('fmfp_employer_rate', models.DecimalField(decimal_places=4, default=0.01, max_digits=5, verbose_name='Taux FMFP Patronal')),
                ('smids_amount', models.DecimalField(decimal_places=2, default=250000.0, max_digits=10, verbose_name='Montant de référence SMIDS (Ar)')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_settings', to='accounts.company')),
            ],
        ),
    ]
