# Generated by Django 5.2.17 on 2026-08-18 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_payrollsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollsettings',
            name='smids_amount',
        ),
    ]
