# Generated by Django 5.2.17 on 2026-08-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_remove_payrollsettings_smids_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='smids_employee_rate',
            field=models.DecimalField(decimal_places=4, default=0.01, max_digits=5, verbose_name='Taux SMIDS Salarié'),
        ),
    ]
