# Generated by Django 5.2.17 on 2026-08-19 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_payrollsettings_smids_employee_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('shift', models.CharField(choices=[('morning', 'Matin (1/60)'), ('afternoon', 'Après-midi (1/60)'), ('night', 'Nuit (1/60)'), ('full_day', 'Journée complète (1/30)')], max_length=20, verbose_name='Tranche / Période')),
                ('is_excused', models.BooleanField(default=False, verbose_name='Congé / Absence autorisée (non déductible)')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='payroll.employee', verbose_name='Salarié')),
            ],
            options={
                'verbose_name': 'Suivi de présence / absence',
                'verbose_name_plural': 'Suivis des présences et absences',
                'unique_together': {('employee', 'date', 'shift')},
            },
        ),
    ]
